# Generated by Django 4.2.4 on 2023-09-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10, verbose_name='OTP code')),
                ('phone_number', models.CharField(max_length=30, verbose_name='PhoneNumber')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date When Modified')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Is Validate')),
                ('validate_attempt', models.IntegerField(default=3, verbose_name='Attempted Validation')),
                ('reactive_at', models.DateTimeField(verbose_name='ReActivate Sending OTP')),
                ('send_counter', models.IntegerField(default=0, verbose_name='OTP Sent Counter')),
                ('timeout', models.DateTimeField(verbose_name='Time out')),
            ],
            options={
                'verbose_name': 'OTP Validation',
                'verbose_name_plural': 'OTP Validations',
            },
        ),
    ]
