# Generated by Django 4.2.4 on 2023-08-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('unique_name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('email', 'Mail'), ('webhook', 'Webhook'), ('sms', 'SMS'), ('slack', 'Slack')], default='email', max_length=30)),
                ('receiver_field', models.CharField(max_length=200)),
                ('slack_channel', models.CharField(blank=True, max_length=50)),
                ('isSubscribed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel', to='users.users')),
            ],
        ),
    ]
